Description: >-
  Deploys Auto Scaling
  Subnets, AZs and launch configuration name should be parameterized

Parameters:

  ARNTargetGroup:
    Description: ARN of an existing target group
    Type: String

  LaunchConfigName:
    Description: Launch configuration name 
    Type: String

  Subnets:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>


Resources:
  ec2testas:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Ref AWS::StackName
      DesiredCapacity: '1'
      MinSize: '1'
      MaxSize: '2'
      LaunchConfigurationName: !Ref  LaunchConfigName 
      VPCZoneIdentifier: !Ref Subnets
      HealthCheckType: 'ELB'
      TargetGroupARNs: [ !Ref ARNTargetGroup]
      HealthCheckGracePeriod : 300

     # LoadBalancerNames: "ec2-test-alb"
