AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to create a role for ec2 instance, access to ec2 and cloudWatch
Resources:
  ec2role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Sub ec2rolepolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'ec2:Describe*'
                  - 'ec2:CreateImage'
                  - 'ec2:CreateSnapshot'
                  - 'ec2:CreateTags'
                  - 'ec2:CreateVolume'
                  - 'ec2:ModifyInstanceAttribute'
                  - 'ec2:RunInstances'
                  - 'ec2:StartInstances'
                  - 'ec2:StopInstances'
                  - 'ec2:AttachVolume'
                Effect: Allow
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogStreams'
                Resource:
                  - 'arn:aws:logs:*:*:*'
      RoleName: !Sub ec2role
  RootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref ec2role
      InstanceProfileName: !Sub ec2roleprofile
Outputs:
  Profilearn:
    Description: Instance profile name of ec2roleprofile
    Value: !GetAtt 
      - RootInstanceProfile
      - Arn
    Export:
      Name: !Sub ec2roleprofile

